id: A9E67C2A6
title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good Actions”
  (Zangchö Mönlam)'
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:10:22.651784
  last_modified_at: 2022-03-01 06:10:22.651788
