id: A9E67C2A6
title: The Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:10:22.655270
  last_modified_at: 2022-03-01 06:10:22.655273
