id: A9E67C2A6
title: 'The Fulfilment of All Aspirations: In Praise of Noble Tārā'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:10:22.644336
  last_modified_at: 2022-03-01 06:10:22.644339
