id: A9E67C2A6
title: Taking the Vows of Sojong
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:10:22.640342
  last_modified_at: 2022-03-01 06:10:22.640345
