id: A9E67C2A6
title: Maitreya's Aspiration
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:10:22.637870
  last_modified_at: 2022-03-01 06:10:22.637921
