id: A9E67C2A6
title: The Auspicious Verses of the Seven Successive Buddhas
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:10:22.642128
  last_modified_at: 2022-03-01 06:10:22.642131
